import type { Metadata } from 'next';

import '../styles/globals.scss';
import Header from '../components/widgets/Header/Header';
import Modal from '../components/widgets/Modal/Modal';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <div className='container'>
          <Header />
          {children}
        </div>
        <Modal />
      </body>
    </html>
  );
}
